### ISSUE TITLE
are slices guaranteed to all be within the same namespace?

### ISSUE THREAD

**Issue by NickFranceschina** [GoogleCloudPlatform/appengine-mapreduce#104]
Trying to decipher the code... but I thought I would ask anyways:  when a batch of datastore entities in a slice are sent to the map/reduce callbacks... are all of those entities in the batch guaranteed to be in the same namespace?   I ask because A) we have some code that relies on the  namespace being set before it runs... and B) we have async Operations/pool in play in our map/reduce callbacks... so it would be problematic to do, per callback, `namespace_manager.set_namespace('xxx')` and `yield PutAsync(entity)`... since by the time the actual `puts` are done by the pool, the default namespace would be indeterminate

hopefully that makes sense

**Comment by aozarov** [comment]
I am not that familiar with the Python code (I used to work on the Java MR), but I am pretty sure that even in Python once an entity is constructed it captures the *current* namespace as part of the key and it does not matter what the *current* namespace is when you put it.

It does not look like the Python MR will sets the current namespace to the namespace of the entity that it invoke `map` with (but that should be easy to check).

**Comment by NickFranceschina** [comment]
this is probably a python-specific implementation question.  I'll try to rephrase:  say that every time the map function is called, I set the current namespace (or MR does it before calling me)... I make some changes and do a `yield Put(entity)` which puts the entity into the mutation pool.  If there were 10 entities in the batch (slice?) I may have set the current namespace 10 different times.  Then at the end, the mutation pool flushes and does the actual `.put()` on each entity... but at the time it does that, the current namespace is set to whatever the last entity into the map call was...  so if there is any custom code within any of the `def put(self)` overrides or whatever... all of that code would see a current namespace of the last entity in the batch

now if I know all of the entities in the slice/batch are in the same namespace, then I would expect it to be set once when the batch is retrieved and my map calls can rest assured that all of their work is within a single namespace

**Comment by aozarov** [comment]
I think my previous answer still applies but adding @eddavisson from the Datastore to confirm.
I think that Python would be similar to Java in this regard that once an `entity` is constructed its
key is "pinned" to current namespace. I think it should not matter what is the current namespace
when you actually call put (that entity will not change its namespace to it).

As for MR setting the current namespace to be the same namespace as the entity in the `map` call,
I didn't see that in the code but I guess you verified that?

**Comment by eddavisson** [comment]
@pcostell to confirm, but I think that's correct.

**Comment by pcostell** [comment]
Confirm what Ed and Arie said. When an entity is created as the result of a datastore RPC (Query, Get) the namespace of that entity is set on entity construction. So even if the namespace manager gets set later, re-putting the entities will save the entity in the old namespace.

**Comment by NickFranceschina** [comment]
Yes, I understand that... the namespace is part of the key, and keys are immutable.  I appreciate everyone's feedback , but this isn't the question I'm trying to ask.   Perhaps my terminology is wrong... but let me try a different way:

an MR job is created to map over entities across namespaces (no specific namespace is provided to the MR config).  Shards are determined by breaking up namespaces lexicographically 

https://github.com/GoogleCloudPlatform/appengine-mapreduce/blob/master/python/src/mapreduce/input_readers.py#L356

each of those shards runs, and _I believe_ the terminology is that they do work in "slices"... each slice is a batch of entities matching the input reader specifications/configuration.   So the MR pipeline grabs a batch of entities during a slice and sends those into the map callback one at a time.  

My question:  is it guaranteed that the batch of entities sent into the map callback for a single slice will all be from the same namespace?   or is it possible that some entities in the batch would be from one namespace and others from different namespaces?

the _reason_ I'm asking is because I'm using an asynchronous mutation pool which will do work when it flushes... and some of that work depends on the current namespace being set to whatever all the entities in the pool are set to...  so I'm clearly going to have a problem if batches of entities going into that pool are in different namespaces

**Comment by aozarov** [comment]
No, there is no such "contract" to guaranty that a slice will not span namespaces.

My confusion is regarding the "asynchronous mutation pool", is that your code or are you using
[db.Put](https://github.com/GoogleCloudPlatform/appengine-mapreduce/blob/6e103ac52855c3214de3ec3721d6ec0e7edd5f77/python/src/mapreduce/operation/db.py#L29) which uses [mapreduce.context._MutationPool](https://github.com/GoogleCloudPlatform/appengine-mapreduce/blob/6e103ac52855c3214de3ec3721d6ec0e7edd5f77/python/src/mapreduce/context.py#L216)? As the latter does not depend on the "current namespace".

**Comment by NickFranceschina** [comment]
Thanks @aozarov ... after spending a few days digging through the MR code some more and outlining things... I see that in my setup, a slice will receive a `KeyRangeIterator` and inside of that would be a list of `KeyRange` entities... each of which would have a single namespace, but the overall list could have multiple namespaces... 

and sorry, I should have clarified... "asynchronous mutation pool" is our own code... we actually call it `FuturesPool` and it allows us to yield any type of `@tasklet`.  So when it does a `FuturesPool.flush()` it actually just calls `Future.wait_all(pool_futures)` on the list of tasklets in the pool.   Because our base Model has overridden the `.put_async` and `.delete_async` methods,  to add extra parameters for various things, our `FuturesPool` implementation allows us to do `yield Future(entity.put_async(custom=1, custom="2"))` so we can pass our own params in.... whereas the delivered MR `Operation` does not

Perhaps there's another way we should have been doing it, without having to create this `FuturesPool`?   I'm not sure... this was the best path I could figure out in the time I had
