### ISSUE TITLE
Missing files in latest pypi 1.9.5.0 release

### ISSUE THREAD

**Issue by dalippa** [GoogleCloudPlatform/appengine-mapreduce#14]
The HTML/JS files in mapreduce/third_party/pipeline/ui are missing in the current egg posted to pypi.

Here is a manifest of the files:

lippa@rm-lippa ~/Downloads$ tar tvf GoogleAppEngineMapReduce-1.9.5.0.tar.gz
drwxr-xr-x jlucena/eng       0 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/
-rwxr-xr-x jlucena/eng   17685 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/distribute_setup.py
-rw-r--r-- jlucena/eng      59 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/setup.cfg
-rwxr-xr-x jlucena/eng    1029 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/setup.py
-rwxr-xr-x jlucena/eng     581 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/README
drwxr-xr-x jlucena/eng       0 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/GoogleAppEngineMapReduce.egg-info/
-rw-r--r-- jlucena/eng       1 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/GoogleAppEngineMapReduce.egg-info/dependency_links.txt
-rw-r--r-- jlucena/eng      42 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/GoogleAppEngineMapReduce.egg-info/requires.txt
-rw-r--r-- jlucena/eng    3136 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/GoogleAppEngineMapReduce.egg-info/SOURCES.txt
-rw-r--r-- jlucena/eng     392 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/GoogleAppEngineMapReduce.egg-info/PKG-INFO
-rw-r--r-- jlucena/eng       1 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/GoogleAppEngineMapReduce.egg-info/zip-safe
-rw-r--r-- jlucena/eng      10 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/GoogleAppEngineMapReduce.egg-info/top_level.txt
-rwxr-xr-x jlucena/eng     146 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/MANIFEST.in
-rw-r--r-- jlucena/eng     392 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/PKG-INFO
drwxr-xr-x jlucena/eng       0 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/
-rwxr-xr-x jlucena/eng     600 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/**init**.py
-rwxr-xr-x jlucena/eng    3259 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/main.py
-rwxr-xr-x jlucena/eng    7733 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/mapreduce_pipeline.py
-rwxr-xr-x jlucena/eng  102973 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/input_readers.py
-rwxr-xr-x jlucena/eng    4157 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/key_ranges.py
-rwxr-xr-x jlucena/eng    2274 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/errors.py
-rwxr-xr-x jlucena/eng   12527 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/property_range.py
drwxr-xr-x jlucena/eng       0 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/tools/
-rwxr-xr-x jlucena/eng      22 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/tools/**init**.py
-rwxr-xr-x jlucena/eng    3152 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/tools/gcs_file_seg_reader.py
-rwxr-xr-x jlucena/eng    6049 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/json_util.py
drwxr-xr-x jlucena/eng       0 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/operation/
-rwxr-xr-x jlucena/eng    1613 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/operation/db.py
-rwxr-xr-x jlucena/eng     946 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/operation/**init**.py
-rwxr-xr-x jlucena/eng     982 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/operation/base.py
-rwxr-xr-x jlucena/eng    1296 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/operation/counters.py
-rwxr-xr-x jlucena/eng   15075 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/namespace_range.py
-rwxr-xr-x jlucena/eng   14669 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/context.py
-rwxr-xr-x jlucena/eng   10903 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/file_format_root.py
-rwxr-xr-x jlucena/eng    7406 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/file_format_parser.py
-rwxr-xr-x jlucena/eng    5052 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/mapper_pipeline.py
-rwxr-xr-x jlucena/eng   10140 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/records.py
-rwxr-xr-x jlucena/eng   68593 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/handlers.py
-rwxr-xr-x jlucena/eng   43758 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/output_writers.py
-rwxr-xr-x jlucena/eng   12442 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/status.py
-rwxr-xr-x jlucena/eng    7611 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/parameters.py
drwxr-xr-x jlucena/eng       0 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/
drwxr-xr-x jlucena/eng       0 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/graphy/
-rwxr-xr-x jlucena/eng      40 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/graphy/**init**.py
-rwxr-xr-x jlucena/eng    4022 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/graphy/line_chart.py
-rwxr-xr-x jlucena/eng    6249 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/graphy/pie_chart.py
-rwxr-xr-x jlucena/eng    6837 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/graphy/formatters.py
-rwxr-xr-x jlucena/eng    5814 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/graphy/bar_chart.py
drwxr-xr-x jlucena/eng       0 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/graphy/backends/
-rwxr-xr-x jlucena/eng      22 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/graphy/backends/**init**.py
drwxr-xr-x jlucena/eng       0 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/graphy/backends/google_chart_api/
-rwxr-xr-x jlucena/eng    2098 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/graphy/backends/google_chart_api/**init**.py
-rwxr-xr-x jlucena/eng   14823 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/graphy/backends/google_chart_api/encoders.py
-rwxr-xr-x jlucena/eng    6336 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/graphy/backends/google_chart_api/util.py
-rwxr-xr-x jlucena/eng   14653 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/graphy/common.py
-rwxr-xr-x jlucena/eng     442 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/graphy/util.py
-rwxr-xr-x jlucena/eng      22 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/**init**.py
drwxr-xr-x jlucena/eng       0 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/simplejson/
-rwxr-xr-x jlucena/eng   12383 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/simplejson/**init**.py
-rwxr-xr-x jlucena/eng   15826 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/simplejson/encoder.py
-rwxr-xr-x jlucena/eng   11139 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/simplejson/decoder.py
-rwxr-xr-x jlucena/eng    2271 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/simplejson/scanner.py
-rwxr-xr-x jlucena/eng    5182 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/crc32c.py
drwxr-xr-x jlucena/eng       0 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/pipeline/
-rwxr-xr-x jlucena/eng    1661 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/pipeline/**init**.py
-rwxr-xr-x jlucena/eng  121455 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/pipeline/pipeline.py
-rwxr-xr-x jlucena/eng    1049 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/pipeline/handlers.py
-rwxr-xr-x jlucena/eng    9941 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/pipeline/models.py
-rwxr-xr-x jlucena/eng    6317 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/pipeline/status_ui.py
-rwxr-xr-x jlucena/eng   11461 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/pipeline/common.py
-rwxr-xr-x jlucena/eng    7003 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/third_party/pipeline/util.py
-rwxr-xr-x jlucena/eng   13605 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/file_formats.py
-rwxr-xr-x jlucena/eng   14466 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/datastore_range_iterators.py
-rwxr-xr-x jlucena/eng    8981 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/base_handler.py
-rwxr-xr-x jlucena/eng   22322 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/shuffler.py
drwxr-xr-x jlucena/eng       0 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/api/
-rwxr-xr-x jlucena/eng      22 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/api/**init**.py
drwxr-xr-x jlucena/eng       0 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/api/map_job/
-rwxr-xr-x jlucena/eng   11555 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/api/map_job/abstract_datastore_input_reader.py
-rwxr-xr-x jlucena/eng     681 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/api/map_job/**init**.py
-rwxr-xr-x jlucena/eng    1987 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/api/map_job/shard_life_cycle.py
-rwxr-xr-x jlucena/eng    8737 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/api/map_job/map_job_config.py
-rwxr-xr-x jlucena/eng    5652 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/api/map_job/model_datastore_input_reader.py
-rwxr-xr-x jlucena/eng    3046 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/api/map_job/map_job_context.py
-rwxr-xr-x jlucena/eng    3468 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/api/map_job/sample_input_reader.py
-rwxr-xr-x jlucena/eng    1906 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/api/map_job/mapper.py
-rwxr-xr-x jlucena/eng    3943 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/api/map_job/input_reader.py
-rwxr-xr-x jlucena/eng    5283 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/api/map_job/output_writer.py
-rwxr-xr-x jlucena/eng    6845 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/api/map_job/map_job_control.py
-rwxr-xr-x jlucena/eng    1273 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/api/map_job/datastore_input_reader.py
-rwxr-xr-x jlucena/eng    7022 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/test_support.py
-rwxr-xr-x jlucena/eng   12371 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/util.py
-rwxr-xr-x jlucena/eng   39511 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/model.py
drwxr-xr-x jlucena/eng       0 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/lib/
-rwxr-xr-x jlucena/eng      74 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/lib/**init**.py
drwxr-xr-x jlucena/eng       0 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/lib/input_reader/
-rwxr-xr-x jlucena/eng     272 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/lib/input_reader/**init**.py
-rwxr-xr-x jlucena/eng   13896 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/lib/input_reader/_gcs.py
-rwxr-xr-x jlucena/eng    3246 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/hooks.py
-rwxr-xr-x jlucena/eng     800 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/pipeline_base.py
-rwxr-xr-x jlucena/eng    4559 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/control.py
drwxr-xr-x jlucena/eng       0 2014-06-02 14:16 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/static/
-rwxr-xr-x jlucena/eng   19863 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/static/status.js
-rwxr-xr-x jlucena/eng    1470 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/static/detail.html
-rwxr-xr-x jlucena/eng   91344 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/static/jquery-1.6.1.min.js
-rwxr-xr-x jlucena/eng    1509 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/static/base.css
-rwxr-xr-x jlucena/eng    2247 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/static/jquery.json-2.2.min.js
-rwxr-xr-x jlucena/eng    7270 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/static/jquery.url.js
-rwxr-xr-x jlucena/eng    1485 1980-01-01 02:00 GoogleAppEngineMapReduce-1.9.5.0/mapreduce/static/overview.html

**Comment by john2x** [comment]
Where exactly in the wiki is this noted?
