### ISSUE TITLE
A minimalistic tutorial

### ISSUE THREAD

**Issue by MeLight** [GoogleCloudPlatform/appengine-mapreduce#15]
Would be pretty amazing if someone from the maintainers of this repo would write a simple tutorial with the bare minimums to run a map-reduce job on [python flavored] app engine, covering these issues:
* Which handlers are absolutely needed (For map and reduce, or only for map)
* What should they accept/return
* How to configure the corresponding mapreduce.yaml
* Also, it would probably be **very** useful to show how it's used on a [large] database

![dvr7v](https://cloud.githubusercontent.com/assets/704484/4944848/90802df6-6601-11e4-8cbf-09f6ec1a4d1f.jpg)

Thanks!

**Comment by MeLight** [comment]
Finally got to giving it a spin. The tutorial looks great and informative, but feels a bit outdated (sends users to get the MapReduce library from the SVN repo). I've also spent about half an hour configuring all the dependencies until I could finally run the demo (build_demo? run_demo?). Also feels like the demo setup has lots of irrelevant code.

**Comment by tkaitchuck** [comment]
I am not able to reproduce that particular error. It could be there is another instance of the dev-appserver running on the same machine. That would likely cause the error you're seeing.

**Comment by MeLight** [comment]
Hi again,
I've finally written a super simple starter tutorial for mapping (iterating) over an entity kind in the datastore. Can be found here:

http://wisestamp.com/blog/mapreduce-on-app-engine-made-easy/
