### ISSUE TITLE
Python package data are not installed 

### ISSUE THREAD

**Issue by dinoboff** [GoogleCloudPlatform/appengine-mapreduce#30]
GoogleAppEngineMapReduce 1.9.16.1 package on pypi includes the include.yaml and the UI files but they are not getting installed.

**Comment by dinoboff** [comment]
To test it:
```
virtualenv -p python2.7 pyenv
pip install GoogleAppEngineMapReduce -t ./lib
cat lib/GoogleAppEngineMapReduce-1.9.16.1-py2.7.egg-info/SOURCES.txt
ls -la lib/mapreduce/
```

To check the data file where included in the package, we can check SOURCES.txt in the package egg:
    
    $ cat lib/GoogleAppEngineMapReduce-1.9.16.1-py2.7.egg-info/SOURCES.txt | grep include.yaml
    mapreduce/include.yaml
    $ cat lib/GoogleAppEngineMapReduce-1.9.16.1-py2.7.egg-info/SOURCES.txt | grep static/
    mapreduce/static/base.css
    mapreduce/static/detail.html
    mapreduce/static/jquery-1.6.1.min.js
    mapreduce/static/jquery.json-2.2.min.js
    mapreduce/static/jquery.url.js
    mapreduce/static/overview.html
    mapreduce/static/status.js

However they didn't get installed:

    $ ls -la lib/mapreduce/include.yaml
    ls: lib/mapreduce/include.yaml: No such file or directory
    $ ls -la lib/mapreduce/static/
    ls: lib/mapreduce/static/: No such file or directory

**Comment by mapi** [comment]
this commit include static data
https://github.com/GoogleCloudPlatform/appengine-mapreduce/commit/da8b508d79b6eb5467c8304fd9786f821d1a81e5#diff-b2c0ca819d00947c35cd1b3fca187fcaR27

but this commit removed that
https://github.com/GoogleCloudPlatform/appengine-mapreduce/commit/a1844a2652d51c3bef4448c9265c7c5790c9e476#diff-b2c0ca819d00947c35cd1b3fca187fcaL27
