### ISSUE TITLE
Cannot reassign a Pipeline to use a specific push task queue

### ISSUE THREAD

**Issue by dalippa** [GoogleCloudPlatform/appengine-mapreduce#33]
The only place I saw where this could be "overridden" is in the start() method, which works on the local dev_appserver but not with certain Mapreduce jobs on a deployed GAE environment.

It would seem this would need to be able to be added to with_params() to override the default task queue, along with the default target.

**Comment by tkaitchuck** [comment]
It depends what you mean by overriding the queue. This: https://github.com/GoogleCloudPlatform/appengine-mapreduce/blob/de86c28ae80877b3b4ba0d5e90eca63ae6100bd2/python/test/mapreduce/parameters_test.py#L106
works. I assume you mean you want the pipeline off the default queue entirely even for the wrapping pipeline. I don't personally know the python code well enough to definitively state if that is possible. But if you want to change it feel free to send a pull request.

**Comment by dalippa** [comment]
I spoke with Google, and apparently the queue_name is not propagated to child pipelines. I had to subclass PipelineBase, MapreducePipeline, and MapperPipeline - and override the start() method there.

No pull request is absolutely needed, though it might be nice to have a way for child pipelines to inherit the task queues of their parents.

**Comment by tkaitchuck** [comment]
Ah, ok. That makes sense. Closing this in favor of https://github.com/GoogleCloudPlatform/appengine-pipelines/issues/17
