### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by xlevus** [GoogleCloudPlatform/appengine-mapreduce#34]
As of the [1.9.16.1](https://pypi.python.org/packages/source/G/GoogleAppEngineMapReduce/GoogleAppEngineMapReduce-1.9.16.1.tar.gz#md5=eb657d3c4d8b492e40795db9d14394dd) release, the documentation available on [the wiki](https://github.com/GoogleCloudPlatform/appengine-mapreduce/wiki/3.4-Readers-and-Writers) is severely out of date.

Both ``BlobstoreOutputWriter`` and ``FileOutputWriter`` are no longer in the source, and none of the output writers in the source are mentioned in the documentation.

**Comment by john2x** [comment]
Where is `FileOutputWriter` now? Is it replaced by something else? I need it for a job.

**Comment by xlevus** [comment]
Related Issue: https://github.com/GoogleCloudPlatform/appengine-mapreduce/issues/26

**Comment by someone1** [comment]
It is a wiki... I updated it, feel free to embellish as you see fit!
