### ISSUE TITLE
Don't try to import simplejson on Python 2.6+

### ISSUE THREAD

**Issue by Kazade** [GoogleCloudPlatform/appengine-mapreduce#36]
In Python 2.6+, simplejson is superseded by json. appengine-mapreduce should do something like:

    try:
        import json
    except:
        import simplejson as json

So that we aren't required to bundle simplejson with our apps when we want to use mapreduce

**Comment by nickfirespotter** [comment]
I agree, this is pretty annoying.

**Comment by sadovnychyi** [comment]
Just made a PR, reviews are welcome. :eyes:
