### ISSUE TITLE
charts4j charts do not show up - getting ParameterInstantiationException

### ISSUE THREAD

**Issue by StefanieScherzinger** [GoogleCloudPlatform/appengine-mapreduce#40]
I am running Java AppEngine MapReduce, latest version as included by Maven.
I am running the ChainedMapReduce Job example from the tutorial.

The MapReduce jobs complete, but the visualizing graphs do not show up.
The browser shows the message

>>>
com.googlecode.charts4j.parameters.ParameterManager$ParameterInstantiationException: Full stack trace is available in the server logs. Message: Internal error: Could not instatiate com.googlecode.charts4j.parameters.DataParameter
<<<
The Eclipse console shows the exception

>>>
[INFO] SEVERE: Got exception while running command
[INFO] com.googlecode.charts4j.parameters.ParameterManager$ParameterInstantiationException: Internal error: Could not instatiate com.googlecode.charts4j.parameters.DataParameter
[INFO] 	at com.googlecode.charts4j.parameters.ParameterManager.getParameter(ParameterManager.java:600)
[INFO] 	at com.googlecode.charts4j.parameters.ParameterManager.setDataEncoding(ParameterManager.java:429)
[INFO] 	at com.googlecode.charts4j.AbstractGChart.prepareData(AbstractGChart.java:198)
[INFO] 	at com.googlecode.charts4j.AbstractGraphChart.prepareData(AbstractGraphChart.java:107)
[INFO] 	at com.googlecode.charts4j.AbstractAxisChart.prepareData(AbstractAxisChart.java:177)
[INFO] 	at com.googlecode.charts4j.BarChart.prepareData(BarChart.java:119)
[INFO] 	at com.googlecode.charts4j.AbstractGChart.toURLString(AbstractGChart.java:130)
[INFO] 	at com.google.appengine.tools.mapreduce.impl.handlers.StatusHandler.getChartUrl(StatusHandler.java:153)
[INFO] 	at com.google.appengine.tools.mapreduce.impl.handlers.StatusHandler.handleGetJobDetail(StatusHandler.java:223)
[INFO] 	at com.google.appengine.tools.mapreduce.impl.handlers.StatusHandler.handleCommand(StatusHandler.java:92)
[INFO] 	at com.google.appengine.tools.mapreduce.impl.handlers.MapReduceServletImpl.doGet(MapReduceServletImpl.java:86)
[INFO] 	at com.google.appengine.tools.mapreduce.MapReduceServlet.doGet(MapReduceServlet.java:71)
...
<<<

I added charts4j as a Maven dependency, but that did not resolve the problem.

Stefanie

**Comment by aozarov** [comment]
Can you verify that you don't have/include older versions of the charts4j library.
Looks like com.googlecode.charts4j.parameters.DataParameter is missing (can't be found by com.googlecode.charts4j.parameters.ParameterManager).

**Comment by StefanieScherzinger** [comment]
Indeed I had older versions present, included via some other jar. Issue
resolved, thanks.
