### ISSUE TITLE
Python: How to add mapreduce to existing App Engine project?

### ISSUE THREAD

**Issue by pipacs** [GoogleCloudPlatform/appengine-mapreduce#53]
Tried to copy src/mapreduce to my project folder, then include include.yam from the my yaml. But when starting up dev_appserver, got this exception;

    from graphy.backends import google_chart_api
    ImportError: No module named graphy.backends

Then I tried build.sh, but it can only build the demo app and nothing else.

Additionally, build.sh installed a huge amount of redundant packages, like graphy, simplejson etc., directly into the demo folder.

**Comment by Peter2013Aug** [comment]
you need to put graphy under your project folder

**Comment by pipacs** [comment]
Thanks for the answer. Dependency management could be a bit smarter though, as many of the packages, like graph, are already distributed with the App Engine SDK.
