### ISSUE TITLE
Please add license headers to all files

### ISSUE THREAD

**Issue by anniesullie** [GoogleCloudPlatform/appengine-mapreduce#71]
Some chromium dependencies import this project and would require the presence of valid license headers in all source files.

Files that are missing license headers:

mapreduce/lib/__init__.py
mapreduce/lib/input_reader/__init__.py
mapreduce/lib/input_reader/_gcs.py
mapreduce/property_range.py
mapreduce/datastore_range_iterators.py
mapreduce/shard_life_cycle.py
mapreduce/records.py
mapreduce/api/map_job/mapper.py
mapreduce/api/map_job/map_job_control.py
mapreduce/api/map_job/output_writer.py
mapreduce/api/map_job/input_reader.py
mapreduce/api/map_job/abstract_datastore_input_reader.py
mapreduce/api/map_job/datastore_input_reader.py
mapreduce/api/map_job/sample_input_reader.py
mapreduce/api/map_job/__init__.py
mapreduce/api/map_job/model_datastore_input_reader.py
mapreduce/api/__init__.py
mapreduce/key_ranges.py
mapreduce/tools/gcs_file_seg_reader.py
mapreduce/mapreduce/tools/__init__.py
mapreduce/map_job_context.py
mapreduce/parameters.py
mapreduce/pipeline_base.py
mapreduce/json_util.py

**Comment by tkaitchuck** [comment]
Please send a pull request.
