### ISSUE TITLE
Documentation: how to configure shardCount?

### ISSUE THREAD

**Issue by mingtaozhangsc** [GoogleCloudPlatform/appengine-mapreduce#81]
When set shardCount, should I assume it's related to -PgaeInstances=10? Or the instances are allocated in other fashion?

**Comment by aozarov** [comment]
MR `shardCount` X means that the overall input for the `map` stage will be divided by X shards.

An MR shard is a unit of work that is processed sequentially (triggered by one or more sequential taskqueue tasks, each of which is called a `slice`).

Multiple shards can work in parallel to each other, but that **depends on** your queue settings and the instance configuration rather than control it.

**Comment by mingtaozhangsc** [comment]
@aozarov Thank you!
I noticed there are two ways of using MR. One is use the task queue, which will suffer 60 sec time out. The other is still in beta, and it's the one I am currently using.
```
import com.google.appengine.tools.mapreduce.MapJob;
import com.google.appengine.tools.mapreduce.MapOnlyMapper;
import com.google.appengine.tools.mapreduce.MapSpecification;
import com.google.appengine.tools.mapreduce.MapSettings;
import com.google.appengine.tools.mapreduce.inputs.DatastoreInput;
```
Could you elaborate how #instances and shard related in this use case? or maybe point me to some docs?

**Comment by aozarov** [comment]
@mingtaozhangsc I am not sure what are the 2 ways you are referring to.

The AE MR library always used the task queue for executing its work.
Task queue is bounded to 10 minutes when invoked on front-ends or 24 hours when sent to a backend type instance.

The number of shards for an MR job is the maximum level of parallelism for that job and there would
be that many task-queue tasks sent.

The applications configuration for the task queue and instances, including any other work-load sent
on these resources, will affect how many of the job's tasks are *actually* exected in parallel.

**Comment by mingtaozhangsc** [comment]
@aozarov Thank you!
