### ISSUE TITLE
java: using shuffle stage

### ISSUE THREAD

**Issue by mgenov** [GoogleCloudPlatform/appengine-mapreduce#86]
The documentation says that the shuffle stage is supported: https://github.com/GoogleCloudPlatform/appengine-mapreduce/wiki/1.2-Jobs-and-Stages#shuffle

but I cannot find an API for using this stage. Can anyone give some clues ?

**Comment by tkaitchuck** [comment]
When you run a map reduce you supply the mapper and the reducer. The shuffle is the same for all jobs so it is supplied by the library. You don't need to interact with it.

**Comment by mgenov** [comment]
I think that I've got the expected result in my sample app. Thanks !
